### PR TITLE
banner updated

### PR DESCRIPTION
**Pull request by maharshi-gor**
This PR updates the banner for DIPY workshop 2024.

### CODE REVIEW

**Comment by skoudoro** [comment]
Can you update the README File instructions in this PR also ?

please keep both (banner folder or url)

**Comment by skoudoro** [comment]
Otherwise, the typography of the text is quite horrible. Can you improve the typography. look below:

image

**Comment by skoudoro** [comment]
I mean, the typography of the banner does not match with the website, and look weird

**Comment by maharshi-gor** [comment]
> I mean, the typography of the banner does not match with the website, and look weird

We tried for the same I can get the fonts let me see if I can get

**Review by skoudoro — APPROVED** [review]
Much better! Thanks!

merging

**Pull request merged**
