### PR TITLE
DOC: Blogpost_KD_Week0

### PR DESCRIPTION
**Pull request by deka27**
Summary:
This pull request introduces a new blog post detailing the Google Summer of Code (GSoC) community bonding period. It aims to provide insights and reflections for future work.

Key Changes:

- Added a new blog post file in the posts/2024 directory.

@itellaetxe @robinroy03 @WassCodeur

### CODE REVIEW

**Comment by deka27** [comment]
Codespell issue is due to blog post in previous year.

**Comment by deka27** [comment]
> > Codespell issue is due to blog post in previous year.
> 
> ok, thank you for catching that. So be pro active 😅 . Please, fix it in a new pull request and then rebase your pr with your fix

Okay, understood. Will do that now.

**Comment by skoudoro** [comment]
Great , thank you

**Review by itellaetxe — COMMENTED** [review]
From line 9 to the end, 4004 characters, just like the maximum for the Mastodon server. Good.

LGTM!

**Comment by robinroy03** [comment]
LGTM :)

**Comment by deka27** [comment]
I have squashed the commits.

**Review by skoudoro — APPROVED** [review]
I was waiting for the review of @WassCodeur,

But it looks good. I will go ahead and merge this PR. Thank you @deka27 and thank for the reviewers

**Pull request merged**
